# Generated by Django 3.1.13 on 2021-11-07 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='apps',
        ),
        migrations.AddField(
            model_name='server',
            name='apps',
            field=models.ManyToManyField(to='server.Aplicativos'),
        ),
    ]
